import { useEffect,useState } from 'react';
import { listKnowledgeBases,createKnowledgeBase,uploadKnowledgeDocument,searchKnowledgeBase } from '../api/agentApi';
import type { KnowledgeBase,KnowledgeDocument,KnowledgeSearchResult } from '../api/agentApi';
import './Pages.css';

export default function KnowledgeBasePage(){
 const [bases,setBases]=useState<KnowledgeBase[]>([]); const [selected,setSelected]=useState(''); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [file,setFile]=useState<File|null>(null); const [uploaded,setUploaded]=useState<KnowledgeDocument|null>(null); const [query,setQuery]=useState(''); const [results,setResults]=useState<KnowledgeSearchResult[]>([]); const [loading,setLoading]=useState(true); const [creating,setCreating]=useState(false); const [uploading,setUploading]=useState(false); const [searching,setSearching]=useState(false); const [message,setMessage]=useState<{text:string;type:'success'|'danger'}|null>(null);
 const load=()=>{setLoading(true);listKnowledgeBases().then(data=>{setBases(data);if(!selected&&data[0])setSelected(data[0].id);}).catch(()=>setMessage({text:'Could not load knowledge bases.',type:'danger'})).finally(()=>setLoading(false));}; useEffect(()=>{load();},[]);
 const notify=(text:string,type:'success'|'danger')=>{setMessage({text,type});setTimeout(()=>setMessage(null),3500)};
 const create=async()=>{if(!name.trim()||creating)return;setCreating(true);try{const x=await createKnowledgeBase(name.trim(),description.trim());setName('');setDescription('');await load();setSelected(x.id);notify('Knowledge base created successfully.','success')}catch{notify('Could not create knowledge base.','danger')}finally{setCreating(false)}};
 const upload=async()=>{if(!selected||!file||uploading)return;setUploading(true);try{const d=await uploadKnowledgeDocument(selected,file);setUploaded(d);setFile(null);await load();notify('Document uploaded and indexing started.','success')}catch{notify('Document upload failed.','danger')}finally{setUploading(false)}};
 const search=async()=>{if(!selected||!query.trim()||searching)return;setSearching(true);try{setResults(await searchKnowledgeBase(selected,query.trim()))}catch{notify('Semantic search failed.','danger')}finally{setSearching(false)}};
 const total=bases.reduce((a,b)=>a+(b.document_count||0),0); const current=bases.find(x=>x.id===selected);
 return <div className="kb-page">
  <header className="page-hero"><div><div className="page-eyebrow">RAG KNOWLEDGE MANAGEMENT</div><h1>Knowledge Base</h1><p>Manage document collections used by retrieval-augmented agents.</p></div><div className="kb-head-stats"><div><strong>{bases.length}</strong><span>Collections</span></div><div><strong>{total}</strong><span>Documents</span></div></div></header>
  {message&&<div className={`page-alert ${message.type}`}>{message.text}<button onClick={()=>setMessage(null)}>×</button></div>}
  <div className="kb-grid">
   <div className="kb-stack">
    <section className="surface-card"><div className="surface-head"><div className="surface-icon purple">+</div><div><h2>Create knowledge base</h2><p>Create a document collection for your RAG agents.</p></div></div><div className="form-grid"><div className="field full"><label>Name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. HR Policies"/></div><div className="field full"><label>Description</label><textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)} placeholder="What documents will this collection contain?"/></div></div><button className="primary-button full" disabled={!name.trim()||creating} onClick={create}>{creating?<><span className="button-spinner"/>Creating...</>:<>+ Create knowledge base</>}</button></section>
    <section className="surface-card"><div className="surface-head"><div className="surface-icon blue">◫</div><div><h2>Your knowledge bases</h2><p>Select a collection to use with upload and search.</p></div></div>{loading?<div className="small-loading"><div className="spinner"/>Loading...</div>:bases.length===0?<div className="mini-empty">No knowledge bases yet.</div>:<div className="kb-list">{bases.map(b=><button className={`kb-list-item ${selected===b.id?'selected':''}`} key={b.id} onClick={()=>{setSelected(b.id);setResults([])}}><div className="kb-letter">{b.name.slice(0,1).toUpperCase()}</div><div className="kb-item-main"><strong>{b.name}</strong><span>{b.document_count} {b.document_count===1?'document':'documents'}</span></div><span className={`status-pill ${b.status?.toLowerCase()==='ready'?'active':'warning'}`}><i/>{b.status}</span>{selected===b.id&&<b className="check">✓</b>}</button>)}</div>}</section>
   </div>
   <div className="kb-stack">
    <section className="surface-card"><div className="surface-head"><div className="surface-icon green">↑</div><div><h2>Upload documents</h2><p>Add source material to the selected collection.</p></div></div><div className="field"><label>Knowledge base</label><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select knowledge base</option>{bases.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div>{current&&<div className="selected-kb"><div className="kb-letter">{current.name.slice(0,1).toUpperCase()}</div><div><strong>{current.name}</strong><span>{current.document_count} indexed documents</span></div></div>}<label className="dropzone"><input type="file" accept=".pdf,.txt,.docx,.csv" onChange={e=>setFile(e.target.files?.[0]||null)}/><div>↑</div><strong>{file?file.name:'Choose a document'}</strong><span>{file?`${(file.size/1024/1024).toFixed(2)} MB ready to upload`:'PDF, TXT, DOCX or CSV · max 20MB'}</span></label><button className="primary-button green full" disabled={!selected||!file||uploading} onClick={upload}>{uploading?<><span className="button-spinner"/>Uploading & indexing...</>:<>↑ Upload & index</>}</button>{uploaded&&<div className="upload-success">✓ {uploaded.filename}<span>{uploaded.chunk_count} chunks</span></div>}<div className="policy-box"><b>Strict RAG policy</b><span>Agents can use retrieved document context from this collection for grounded answers.</span></div></section>
    <section className="surface-card"><div className="surface-head"><div className="surface-icon orange">⌕</div><div><h2>Test semantic search</h2><p>Check whether your documents return relevant context.</p></div></div><div className="search-row"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Ask something about your documents..."/><button className="primary-button" disabled={!selected||!query.trim()||searching} onClick={search}>{searching?'...':'Search'}</button></div>{results.length>0&&<div className="search-results"><div className="results-head"><strong>Retrieved context</strong><span>{results.length} results</span></div>{results.map((r,i)=><div className="search-result" key={i}><div><span>Result {i+1}</span><b>{(r.score*100).toFixed(1)}%</b></div><p>{r.text}</p><div className="score"><i style={{width:`${Math.min(100,Math.max(0,r.score*100))}%`}}/></div></div>)}</div>}</section>
   </div>
  </div>
 </div>;
}
