{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eidiko-chatbot.fullname" . }}-secret
  labels:
    {{- include "eidiko-chatbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  ANTHROPIC_API_KEY: {{ .Values.secret.anthropicApiKey | quote }}
{{- end }}
