apiVersion: v1
kind: Service

metadata:
  name: {{ include "eidiko-chatbot.fullname" . }}

  labels:
    {{- include "eidiko-chatbot.labels" . | nindent 4 }}

spec:

  # ==========================================================
  # C15 - No fixed IP dependency
  # ==========================================================

  type: {{ .Values.service.type }}

  selector:
    {{- include "eidiko-chatbot.selectorLabels" . | nindent 4 }}

  ports:

    - name: http

      protocol: TCP

      # C14
      port: {{ .Values.service.port }}

      # Application container port
      targetPort: {{ .Values.service.targetPort }}
